export default {
  clearday: 'images/clear.png',
  clearnight: 'images/clear.png',
  cloudyday: 'images/cloudy.png',
  cloudynight: 'images/cloudy.png',
  humidday: 'images/humid.png',
  humidnight: 'images/humid.png',
  ishowerday: 'images/ishower.png',
  ishowernight: 'images/ishower.png',
  lightrainday: 'images/lightrain.png',
  lightrainnight: 'images/lightrain.png',
  mcloudyday: 'images/mcloudy.png',
  mcloudynight: 'images/mcloudy.png',
  oshowerday: 'images/oshower.png',
  oshowernight: 'images/oshower.png',
  pcloudyday: 'images/pcloudy.png',
  pcloudynight: 'images/pcloudy.png',
  rainsnownight: 'images/rainsnow.png',
  snowday: 'images/snow.png',
  snownight: 'images/snow.png',
  rainday: 'images/rain.png',
  rainnight: 'images/rain.png',
  tsrainday: 'images/tsrain.png',
  tstormday: 'images/tstorm.png',
  tsstormnight: 'images/tstorm.png',
  windy: 'images/windy.png',
};
