export default {
  clearday: 'Clear',
  clearnight: 'Clear',
  cloudyday: 'Cloudy',
  cloudynight: 'Cloudy',
  humidday: 'Humid',
  humidnight: 'Humid',
  ishowerday: 'Isolated Shower',
  ishowernight: 'Isolated Shower',
  lightrainday: 'Light Rain',
  lightrainnight: 'Light Rain',
  mcloudyday: 'Mostly Cloudy',
  mcloudynight: 'Mostly Cloudy',
  oshowerday: 'Occasional Shower',
  oshowernight: 'Occasional Shower',
  pcloudyday: 'Partly Cloudy',
  pcloudynight: 'Partly Cloudy',
  rainsnownight: 'Rain and Snow',
  snowday: 'Snow',
  snownight: 'Snow',
  rainday: 'Rain',
  rainnight: 'Rain',
  tsrainday: 'Thunderstorm with Rain',
  tstormday: 'Thunderstorm',
  tsstormnight: 'Thunderstorm',
  windy: 'Windy',
};
