export default {
  clearday: '../src/images/clear.png',
  clearnight: '../src/images/clear.png',
  cloudyday: '../src/images/cloudy.png',
  cloudynight: '../src/images/cloudy.png',
  humidday: '../src/images/humid.png',
  humidnight: '../src/images/humid.png',
  ishowerday: '../src/images/ishower.png',
  ishowernight: '../src/images/ishower.png',
  lightrainday: '../src/images/lightrain.png',
  lightrainnight: '../src/images/lightrain.png',
  mcloudyday: '../src/images/mcloudy.png',
  mcloudynight: '../src/images/mcloudy.png',
  oshowerday: '../src/images/oshower.png',
  oshowernight: '../src/images/oshower.png',
  pcloudyday: '../src/images/pcloudy.png',
  pcloudynight: '../src/images/pcloudy.png',
  rainsnownight: '../src/images/rainsnow.png',
  snowday: '../src/images/snow.png',
  snownight: '../src/images/snow.png',
  rainday: '../src/images/rain.png',
  rainnight: '../src/images/rain.png',
  tsrainday: '../src/images/tsrain.png',
  tstormday: '../src/images/tstorm.png',
  tsstormnight: '../src/images/tstorm.png',
  windy: '../src/images/windy.png',
};
